Username: "test"
toolsDomain: "tools.example.com"

aws:
  iamRole: ""
  defaultRegion: "eu-west-1"
  accountID: "593291632749"
service:
  port: 80

proxy:
  port: 3000
  auth0:
    clientSecret: ""
    clientId: ""
    domain: "AUTH0_USER.eu.auth0.com"
    logoutUrl: "https://controlpanel.services.alpha.mojanalytics.xyz/"

  image:
    repository: ministryofjustice/nginx-proxy-jupyter
    tag: "0.0.1"
    pullPolicy: "IfNotPresent"
  resources:
    limits:
      cpu: 1
      memory: 128Mi
    requests:
      cpu: 0.5
      memory: 128Mi

jupyter:
  image: ministryofjustice/datascience-notebook
  tag: v3.1.13
  imagePullPolicy: IfNotPresent
  containerPort: 8888
  resources:
    limits:
      cpu: 1.5
      memory: 12Gi
    requests:
      cpu: 1.5
      memory: 12Gi

cookie_secret: ""
