# permissions for end users to edit airflows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: airflow-editor-role
rules:
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - airflows
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - airflows/status
  verbs:
  - get
