# permissions for end users to edit rstudios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rstudio-editor-role
rules:
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - rstudios
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - rstudios/status
  verbs:
  - get
