# permissions for end users to view rstudios.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rstudio-viewer-role
rules:
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - rstudios
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - rstudios/status
  verbs:
  - get
