# permissions for end users to view tools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tool-viewer-role
rules:
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - tools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - tools/status
  verbs:
  - get
