# permissions for end users to edit tools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tool-editor-role
rules:
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - tools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tools.analytical-platform.justice
  resources:
  - tools/status
  verbs:
  - get
