apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: analytical-platform-tools-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: JupyterLab is the Schema for the jupyterlabs API
      displayName: Jupyter Lab
      kind: JupyterLab
      name: jupyterlabs.tools.analytical-platform.justice
      version: v1alpha1
    - description: Tool is the Schema for the tools API
      displayName: Tool
      kind: Tool
      name: tools.tools.analytical-platform.justice
      version: v1alpha1
  description: An operator used by ministryofjustice/analytical-platform to create,
    manage and maintain MI tools
  displayName: tools-operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - go
  - mi
  - jupyterlab
  - airflow
  links:
  - name: Analytical Platform Tools Operator
    url: https://analytical-platform-tools-operator.domain
  maturity: alpha
  provider:
    name: tools-operator
  version: 0.0.0
