# permissions for end users to view jupyterlabdatasciencenotebooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jupyterlabdatasciencenotebook-viewer-role
rules:
- apiGroups:
  - charts.analytical-platform.justice
  resources:
  - jupyterlabdatasciencenotebooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - charts.analytical-platform.justice
  resources:
  - jupyterlabdatasciencenotebooks/status
  verbs:
  - get
