# Deploys are performed by the kustomize controller on the Dev EKS infrustructure.
# To successfully deploy, we need to have an image in an image registry and the kustomize
# manifest pointing at the correct place.
name: Production Build, Test, Push and Deploy

on:
  release:
    types: [created]

env:
  IMAGE: ministryofjustice/analytical-platform-tools-operator

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17" # The Go version to download (if necessary) and use.

      - name: Install environment binaries
        run: |
          make controller-gen kustomize envtest

      - name: Test with envtest
        run: |
          make test

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF}
          echo "::set-output name=BUILD_ID::${branch}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish container image with tag
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
