# Deploys are performed by the kustomize controller on the Dev EKS infrustructure.
# To successfully deploy, we need to have an image in an image registry and the kustomize
# manifest pointing at the correct place.
name: Non-production Build, Test, Push and Deploy

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "**.md"
      - ".github/**"
      - "Makefile"

env:
  IMAGE: ministryofjustice/analytical-platform-tools-operator

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.1
        with:
          ref: main
          fetch-depth: 0 # To get all tags

      - uses: WillAbides/setup-go-faster@v1.8.0
        with:
          go-version: "1.17.x"

      - name: Perform staticcheck on codebase
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          version: "2022.1"
          install-go: false

      - name: Install environment binaries
        run: |
          make controller-gen kustomize envtest

      - name: Test with envtest
        run: |
          make test

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and publish container image with tag
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: ./Dockerfile
          tags: |
            ${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

      - name: Amend kustomize manifest for dev deploy
        run: |
          cd config/manager && kustomize edit set image controller=${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: build(dev):add git commit hash to kustomize manifest
