name: Test controller

on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.17.9" # The Go version to download (if necessary) and use.

      - name: Install environment binaries
        run: |
          make controller-gen kustomize envtest

      - name: Make test
        run: |
          make test
