name: Non-production Build, Test, Push and Deploy

on:
  workflow_dispatch:
  push:

env:
  ECR_NAME: ${{ secrets.ECR_NAME }}
  VERSION: ${{ github.sha }}

jobs:
  test-build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.17" # The Go version to download (if necessary) and use.

      - name: Install environment binaries
        run: |
          make controller-gen kustomize envtest

      - name: Test with envtest
        run: |
          make test

      - name: Build
        run: docker build -t local .

      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          region: eu-west-2
          local-image: local
          image: ${ECR_NAME}:${VERSION}

      # - name: Deploy to development cluster
